# Generated by Django 6.0.6 on 2026-06-20 19:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('PAID', 'Opłacone'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone'), ('CANCELLED', 'Anulowane')], default='NEW', max_length=20),
        ),
    ]
