# Generated by Django 6.0.6 on 2026-06-20 20:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0006_order_city_order_first_name_order_last_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='tracking_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('PAID', 'Opłacone'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone')], default='NEW', max_length=20),
        ),
        migrations.AlterField(
            model_name='orderstatushistory',
            name='status',
            field=models.CharField(choices=[('NEW', 'Nowe'), ('PAID', 'Opłacone'), ('SHIPPED', 'Wysłane'), ('DELIVERED', 'Dostarczone')], max_length=20),
        ),
    ]
